// wc/spiffworkflow-runner/spiffworkflow-runner.js

class SpiffWorkflowRunner extends HTMLElement {
  static observedAttributes = ["apiKey"];
  apiKey = null;
  completed = false;
  pendingTasks = [];
  runner = 'http://localhost:8100';
  shadow = null;
  state = {};
  status = null;

  slotLoading = document.createElement("slot");
  slotManualTask = document.createElement("slot");

  templateManualTask = document.createElement("template");

  elWorkflow = document.createElement("div");
  
  constructor() {
    super()
  }

  async connectedCallback() {
    this.apiKey = this.getAttribute("apiKey");
    this.shadow = this.attachShadow({ mode: "open" });

    this.initElements();
    this.runWorkflow({});
  }

  async runWorkflow(additionalBody) {
    const resp = await fetch(`${this.runner}/v0/do/${this.apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        ...this.state,
        ...additionalBody,
      }),
    });

    const json = await resp.json();

    this.status = json.status ?? 'error';
    this.completed = json.completed ?? false;
    this.state = { state: json.state ?? {} };
    this.pendingTasks = json.pending_tasks ?? [];

    this.renderPendingTasks();
  }

  renderPendingTasks() {
    const tasksBySpec = this.pendingTasks.reduce((a, c) => ({[c.task_spec.typename]: c, ...a }), {})
    var slots = [];

    if (tasksBySpec.ManualTask) {
      const id = tasksBySpec.ManualTask.id;
      const data = {};
      const taskSpec = tasksBySpec.ManualTask.task_spec;
      const instructions = taskSpec.extensions.instructionsForEndUser;
      
      this.slotManualTask.innerHTML = `
        <p><b>${taskSpec.bpmn_name}</b></p>
        <p>${instructions}</p>
      `

      const completer = document.createElement("button");
      completer.innerText = "Complete";
      completer.onclick = () => this.runWorkflow({ completed_tasks: [{ id, data }]});
      
      this.slotManualTask.appendChild(completer);
      slots.push(this.slotManualTask);
    }

    this.elWorkflow.replaceChildren(...slots);
  }

  initElements() {
    this.slotManualTask.setAttribute("name", "ManualTask");
    this.slotManualTask.innerHTML = '<p>Pending ManualTask...</p>';

    this.shadow.innerHTML = `
      <style>
        .workflow {
          border: solid 1px aqua;
          margin: 3em;
	  padding: 2em;
        }
      </style>
      
      <div id="workflow" class="workflow">
        <slot id="workflowLoadingSlot" name="WorkflowLoading">
          <p>Loading Workflow...</p>
        </slot>
      </div>
    `;

    this.templateManualTask.setAttribute("id", "tmpl-manual-task");
    this.templateManualTask.content.innerHTML = `
      <div>
        <slot name="ManualTaskInstructions">No instructions provided.</slot>
        <button>Complete</button>
      </div>
    `;

    this.slotLoading = this.shadow.getElementById("workflowLoadingSlot");
    
    this.elWorkflow = this.shadow.getElementById("workflow");
    this.elWorkflow.replaceChildren(this.slotLoading);
  }
}

customElements.define('spiffworkflow-runner', SpiffWorkflowRunner)

// lexi/src/components/SpiffWorkflowRunner.tsx
import { useEffect, useState } from 'react'
import { BoundaryEvent } from './BoundaryEvent'
import { ManualTask } from './ManualTask'
import { UserTask } from './UserTask'

interface keyable {
  [key: string]: any; // eslint-disable-line
}

const remoteRunner = "https://myapi.spiff.works"
//const remoteRunner = "http://localhost:8100"

export const SpiffWorkflowRunner = ({ apiKey, schemaMap }: { apiKey: string, schemaMap: keyable }) => {
  const [completed, setCompleted] = useState(false)
  const [error, setError] = useState('')
  const [pendingTasks, setPendingTasks] = useState([])
  const [workflowState, setWorkflowState] = useState({})

  const runWorkflow = async (additionalBody: keyable) => {
    const resp = await fetch(`${remoteRunner}/v0/do/${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        ...workflowState,
        ...additionalBody,
      }),
    })

    const json = await resp.json();

    setCompleted(json.completed ?? false)
    setError(json.message ?? '')
    setPendingTasks(json.pending_tasks ?? [])
    setWorkflowState(json.state ? { state: json.state } : {})
  };

  useEffect(() => {
    runWorkflow({});
  }, []); // eslint-disable-line

  const completeTask = (id: string, data: keyable) => {
    runWorkflow({ completed_tasks: [{ id, data }] })
  };

  const componentForTaskSpec = (task: keyable) =>
    task.task_spec.typename == 'ManualTask' ? (
      <ManualTask
        key={task.id}
        taskId={task.id}
        bpmnId={task.task_spec.bpmn_id}
        taskData={task.data}
        instructions={task.task_spec.extensions.instructionsForEndUser ?? ''}
        completer={completeTask}
      />
    ) : task.task_spec.typename == 'UserTask' ? (
      <UserTask
        key={task.id}
        taskId={task.id}
        bpmnId={task.task_spec.bpmn_id}
        taskData={task.data}
        instructions={task.task_spec.extensions.instructionsForEndUser ?? ''}
        schema={schemaMap[task.task_spec.extensions.properties.formJsonSchemaFilename]}
        uiSchema={schemaMap[task.task_spec.extensions.properties.formUiSchemaFilename]}
        completer={completeTask}
      />
    ) : task.task_spec.typename == 'BoundaryEvent' ? (
      <BoundaryEvent
        key={task.id}
        taskId={task.id}
        bpmnId={task.task_spec.bpmn_id}
        buttonLabel={task.task_spec.extensions.signalButtonLabel ?? 'Boundary Event'}
        completer={completeTask}
      />
    ) : (
      <div key={task.id}>Unsupported task type: {task.task_spec.typename}</div>
    );
  
  return <div className="card">
    {error ? <div className="error">{error}</div>
    :completed === false && pendingTasks.length === 0 ? (
      <div>Loading...</div>
    ) : completed === true ? (
      <div>
        <h3>Workflow Complete!</h3>
        <button
          onClick={() => {
            setWorkflowState({})
            runWorkflow({})
          }}
          data-testid="clear-data"
	>
          Do it again
        </button>
      </div>
    ) : (
      <div>{pendingTasks.map(p => componentForTaskSpec(p))}</div>
    )}
  </div>
}
